Plugins/Nop.Plugin.Shipping.ShipStation/Controllers/ShipStationController.cs
using System;
using System.Globalization;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Shipping.ShipStation.Models;
using Nop.Plugin.Shipping.ShipStation.Services;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Shipping.ShipStation.Controllers
{
    public class ShipStationController : BasePluginController
    {
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;
        private readonly IShipStationService _shipStationService;
        private readonly IStoreContext _storeContext;
        private readonly IWebHelper _webHelper;

        public ShipStationController(ILocalizationService localizationService,
            INotificationService notificationService,
            ISettingService settingService,
            IShipStationService shipStationService,
            IStoreContext storeContext,
            IWebHelper webHelper)
        {
            _localizationService = localizationService;
            _notificationService = notificationService;
            _settingService = settingService;
            _shipStationService = shipStationService;
            _storeContext = storeContext;
            _webHelper = webHelper;
        }
        
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        /// <returns>A task that represents the asynchronous operation</returns>
        public async Task<IActionResult> Configure()
        {
            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var shipStationSettings = await _settingService.LoadSettingAsync<ShipStationSettings>(storeScope);

            var model = new ShipStationModel
            {
                ApiKey = shipStationSettings.ApiKey,
                ApiSecret = shipStationSettings.ApiSecret,
                PackingPackageVolume = shipStationSettings.PackingPackageVolume,
                PackingType = Convert.ToInt32(shipStationSettings.PackingType),
                PackingTypeValues = await shipStationSettings.PackingType.ToSelectListAsync(),
                PassDimensions = shipStationSettings.PassDimensions,
                ActiveStoreScopeConfiguration = storeScope,
                UserName = shipStationSettings.UserName,
                Password = shipStationSettings.Password,
                WebhookURL = $"{_webHelper.GetStoreLocation()}Plugins/ShipStation/Webhook"
            };

            if (storeScope <= 0)
                return View("~/Plugins/Shipping.ShipStation/Views/Configure.cshtml", model);

            model.ApiKey_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.ApiKey, storeScope);
            model.ApiSecret_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.ApiSecret, storeScope);
            model.PackingPackageVolume_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.PackingPackageVolume, storeScope);
            model.PackingType_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.PackingType, storeScope);
            model.PassDimensions_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.PassDimensions, storeScope);
            model.Password_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.Password, storeScope);
            model.UserName_OverrideForStore = await _settingService.SettingExistsAsync(shipStationSettings, x => x.UserName, storeScope);

            return View("~/Plugins/Shipping.ShipStation/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        /// <returns>A task that represents the asynchronous operation</returns>
        public async Task<IActionResult> Configure(ShipStationModel model)
        {
            if (!ModelState.IsValid)
                return await Configure();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var shipStationSettings = await _settingService.LoadSettingAsync<ShipStationSettings>(storeScope);

            //save settings
            shipStationSettings.ApiKey = model.ApiKey;
            shipStationSettings.ApiSecret = model.ApiSecret;
            shipStationSettings.PackingPackageVolume = model.PackingPackageVolume;
            shipStationSettings.PackingType = (PackingType)model.PackingType;
            shipStationSettings.PassDimensions = model.PassDimensions;
            shipStationSettings.Password = model.Password;
            shipStationSettings.UserName = model.UserName;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.ApiKey, model.ApiKey_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.ApiSecret, model.ApiSecret_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.PackingPackageVolume, model.PackingPackageVolume_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.PackingType, model.PackingType_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.PassDimensions, model.PassDimensions_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.Password, model.Password_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(shipStationSettings, x => x.UserName, model.UserName_OverrideForStore, storeScope, false);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

			_notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));
            
            return await Configure();
        }

        /// <returns>A task that represents the asynchronous operation</returns>
        public async Task<IActionResult> Webhook()
        {
            var userName = _webHelper.QueryString<string>("SS-UserName");
            var password = _webHelper.QueryString<string>("SS-Password");

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var shipStationSettings = await _settingService.LoadSettingAsync<ShipStationSettings>(storeScope);

            if (!userName.Equals(shipStationSettings.UserName) || !password.Equals(shipStationSettings.Password))
                return Content(string.Empty);

            var action = _webHelper.QueryString<string>("action") ?? string.Empty;

            if (Request.Method == WebRequestMethods.Http.Post &&
                action.Equals("shipnotify", StringComparison.InvariantCultureIgnoreCase))
            {
                var orderNumber = _webHelper.QueryString<string>("order_number");
                var carrier = _webHelper.QueryString<string>("carrier");
                var service = _webHelper.QueryString<string>("service");
                var trackingNumber = _webHelper.QueryString<string>("tracking_number");

                await _shipStationService.CreateOrUpdateShippingAsync(orderNumber, carrier, service, trackingNumber);

                //nothing should be rendered to visitor
                return Content(string.Empty);
            }

            if (!action.Equals("export", StringComparison.InvariantCultureIgnoreCase))
                return Content(string.Empty);

            var startDateParam = _webHelper.QueryString<string>("start_date");
            var endDateParam = _webHelper.QueryString<string>("end_date");
            var pageIndex = _webHelper.QueryString<int>("page");

            if (pageIndex > 0)
                pageIndex -= 1;

            var startDate = string.IsNullOrEmpty(startDateParam) ? (DateTime?)null : DateTime.ParseExact(startDateParam, _shipStationService.DateFormat, CultureInfo.InvariantCulture);
            var endDate = string.IsNullOrEmpty(endDateParam) ? (DateTime?)null : DateTime.ParseExact(endDateParam, _shipStationService.DateFormat, CultureInfo.InvariantCulture);
            
            return Content(await _shipStationService.GetXmlOrdersAsync(startDate, endDate, pageIndex, 200), "text/xml");
        }
    }
}

Plugins/Nop.Plugin.Shipping.ShipStation/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}

@using Nop.Plugin.Shipping.ShipStation
@model Nop.Plugin.Shipping.ShipStation.Models.ShipStationModel

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="ShipStation" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">

                <h3>Setup Instructions</h3>
                <ul>
                    <li>Register or login on the <strong><a href="https://www.shipstation.com/?ref=partner-nopcommerce&utm_campaign=partner-referrals&utm_source=nopcommerce&utm_medium=partner-referral" target="_blank">ShipStation</a></strong> site</li>
                    <li>Go to the "Settings » API Settings" page and get the <strong>API Key</strong> and the <strong>API Secret</strong> and copy them on the plugin settings</li>
                    <li>Select <strong>Selling Channels</strong> from the left-hand sidebar, then choose <strong>Store Setup</strong>.</li>
                    <li>Click <strong>+ Connect a Store or Marketplace</strong>.</li>
                    <li>Choose the <strong>Custom Store</strong> option</li>
                    <li>Enter the "@Model.WebhookURL" to the <strong>URL to Custom XML Page</strong> setting</li>
                    <li>Create a <strong>Username</strong> and <strong>Password</strong>, enter them into the settings forms (the ShipStation form and the nopCommerce form). <em style="color: red">Do not use the ShipStation or nopCommerce user credentials for this</em>.</li>
                    <li>Don't change the <strong>Statuses</strong> section</li>
                    <li>Save the nopCommerce settings by pressing the <strong>Save</strong> button.</li>
                    <li>On the ShipStation form press Test your connection using the <strong>Test Connection</strong> button</li>
                    <li>Save the settings using the <strong>Connect</strong> button</li>
                </ul>
                <hr />
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ApiKey_OverrideForStore" asp-input="ApiKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ApiKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ApiKey" />
                        <span asp-validation-for="ApiKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ApiSecret_OverrideForStore" asp-input="ApiSecret" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ApiSecret" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ApiSecret" />
                        <span asp-validation-for="ApiSecret"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UserName_OverrideForStore" asp-input="UserName" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UserName" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UserName" />
                        <span asp-validation-for="UserName"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Password_OverrideForStore" asp-input="Password" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Password" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Password" asp-value="@Model.Password" />
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PassDimensions_OverrideForStore" asp-input="PassDimensions" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PassDimensions" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PassDimensions" />
                        <span asp-validation-for="PassDimensions"></span>
                    </div>
                </div>
                <nop-nested-setting asp-for="PassDimensions">
                    <div class="form-group row" id="pnlPackingType">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="PackingType_OverrideForStore" asp-input="PackingType" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="PackingTypeValues" />
                        </div>
                        <div class="col-md-9">
                            <nop-select asp-for="PackingType" asp-items="Model.PackingTypeValues" />
                        </div>
                    </div>
                <nop-nested-setting asp-for="PackingTypeValues">
                    <div class="form-group row" id="pnlPackingPackageVolume">
                        <div class="col-md-3">
                            <nop-override-store-checkbox asp-for="PackingPackageVolume_OverrideForStore" asp-input="PackingPackageVolume" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                            <nop-label asp-for="PackingPackageVolume" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="PackingPackageVolume" />
                            <span asp-validation-for="PackingPackageVolume"></span>
                        </div>
                    </div>
                </nop-nested-setting>
                </nop-nested-setting>
                    <div class="form-group row">
                        <div class="col-md-3">
                            &nbsp;
                        </div>
                        <div class="col-md-9">
                            <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                        </div>
                    </div>

            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    $(document).ready(function() {

        $("#PackingType").change(togglePackingType);

        $(@Html.IdFor(model => model.PassDimensions)).change(togglePassDimensions);

        togglePassDimensions();
    });

    function togglePackingType() {
        var selectedPackingTypeId = $("#PackingType").val();
        if (selectedPackingTypeId == @(((int) PackingType.PackByDimensions).ToString())) {
            $('#pnlPackingPackageVolume').hideElement();
        } else if (selectedPackingTypeId == @(((int) PackingType.PackByVolume).ToString())) {
            $('#pnlPackingPackageVolume').showElement();
        }
    }

    function togglePassDimensions() {
        togglePackingType();
        if ($(@Html.IdFor(model => model.PassDimensions)).is(':checked')) {
            $('#pnlPackingType').showElement();
        } else {
            $('#pnlPackingType').hideElement();
            $('#pnlPackingPackageVolume').hideElement();
        }
    }
</script>